version: "3.6"

services:
  database:
    image: postgres:10.18-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_estate_market
    volumes:
      - ./database/real_estate_market_init.sql:/var/lib/postgresql/real_estate_market_init.sql
      - ./database/postgresql_init.sh:/docker-entrypoint-initdb.d/postgresql_init.sh
    ports:
      - "5433:5432"

  tomcat_server:
    image: tomcat:8.5.81-jre11-openjdk
    container_name: tomcat_server
    restart: always
    volumes:
      - ./real-estate-market.war:/usr/local/tomcat/webapps/real-estate-market.war
    ports:
      - "8081:8080"
    depends_on:
      - database