version: "3.6"

services:
  database:
    image: postgres:10.18-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_estate_market
    volumes:
      - ./database/real_estate_market_init.sql:/var/lib/postgresql/real_estate_market_init.sql
      - ./database/postgresql_init.sh:/docker-entrypoint-initdb.d/postgresql_init.sh
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432

  spring-boot-application:
    image: openjdk:11
    container_name: spring-boot-application
    restart: always
    volumes:
      - ./real-estate-market.jar:/usr/src/real-estate-market.jar
    entrypoint: java -jar /usr/src/real-estate-market.jar
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  pgdata: